### ISSUE TITLE
node_modules/@types/core-js/index.d.ts(2083,39): error TS2339: Property 'replace' does not exist on type 'SymbolConstructor'

### ISSUE THREAD

**Issue by joaojmendes** [koltyakov/sp-pnp-node#1]
After install sp-pnp-node  (npm install sp-pnp-node --save) . on Compile TS I have this kind of errors.

node_modules/@types/core-js/index.d.ts(627,20): error TS2304: Cannot find name 'PromiseConstructor'.
node_modules/@types/core-js/index.d.ts(2083,39): error TS2339: Property 'replace' does not exist on type 'SymbolConstructor'

I have TSC  2.3.4 

Thanks!

**Comment by koltyakov** [comment]
Hi @joaojmendes,

Could you please share your tsconfig.json?
Will [this](https://github.com/koltyakov/sp-pnp-node-demo/tree/master/02-Modes) example work for you without this TS issue?

**Comment by koltyakov** [comment]
I guess that adding `"lib": [ "es6", "dom" ],` to `tsconfig.json` should solve this issue with core-js typings.

**Comment by joaojmendes** [comment]
Hi Koltyakov,

Thank you very much for your quick anwser.

Here my tsconfig.json

`{
  "compilerOptions": {
    "declaration": true,
    "module": "commonjs",
    "moduleResolution": "node",
    "noImplicitAny": true,
    "outDir": "./lib",
    "preserveConstEnums": true,
    "removeComments": true,
    "typeRoots": [
      "./node_modules/@types"
    ]
  },
  "include": [
    "src/**/*"
  ],
  "exclude": [
    "node_modules",
    "**/*-spec.ts"
  ]
}`

Thank you.

**Comment by joaojmendes** [comment]
yes  the problem is resolved .  I added "lib": [ "es6", "dom" ] and now I don't have any error 

Thank you very much!

**Comment by koltyakov** [comment]
You are welcome! Closing the issue.
