### ISSUE TITLE
Javascript Implementation 

### ISSUE THREAD

**Issue by enti333** [koltyakov/sp-pnp-node#10]
Hello. This is not a issue but only maybe questions. 
We are working with pnp-js-core on some solutions but the main problem is that everything must work also on Internet Explorer 11. So because of this and many other things we must to develop our solutions just by simple JavaScript code... and also many things we can not do directly because IE11 doesn't support it....So my question is possible to integrate this by pure javascript...
For example right now if we want to work with pnp-js-core we are using little modified this file...
pnpjs.es5.umd.bundle.min.js and this one polyfill.min.js?callback=stuffisloaded&features=es6|always|gated,fetch|always|gated 
Everything with these little modified files works for us also in Internet Explorer 11. But we don't know how to use this extension... Which files do we need to have uploaded to our library on SharePoint so we can also use this...
I know that we need 
PnPNode.js  but we need also some files from node-sp-auth and node.fetch...and also node-sp-auth-config...

I am very sorry for asking this and I know that in standard environment I will just import full packages and everything starts to work almost automatically but what about this...
Can you please help me with this problem. Thank you

**Comment by koltyakov** [comment]
Hi @enti333, 

To support IE, there is no need in writing code in ES5. Transpilers take care of "compiling" to ES5, while benefiting of modern JavaScript or, what is much better, TypeScript. The [polyfills](https://pnp.github.io/pnpjs/documentation/polyfill/#sharepoint-framework) make some modern language features work in legacy browsers. To simplify such projects I would recommend [sppp generator](https://github.com/koltyakov/generator-sppp), it has preconfigured polyfills, build and bundling tasks, and much more.

I'm not following you how your question is connected with `sp-pnp-node` anyway. The library can only be used in Node.js, not in a browser. IE has no relation to Node.js server-side solutions.

I assume that you have a client-side solution outside SharePoint context, hosted somewhere else, maybe 3rd party system or website, and intention of communication with SharePoint API, don't you?
In such a scenario, if it's SharePoint Online and users have access to SPO's data, AAD OAuth2 authentication flow with ADAL.js or MSAL.js can provide secure access to the API.
For On-Prem or scenarios when users have no direct access to the API, all the SharePoint API communication layer should be placed server-side. The client application talks to a custom backend (e.g. Node.js Express API), the backend authenticates and communicates with SharePoint API.

If you describe your application and authentication flow architecture it can be much easier to suggest a possible solution.

**Comment by enti333** [comment]
Hello. Thank you very much for information about sppp generator. I will try It and it looks nice but I am not sure how will works also with older browsers because the problem was that I must also make some modification of file pnpjs.es5.umd.bundle.min.js but I will try it. Thanks... 
About the node.js...I think that my thoughts were wrong about working with node.js.
My scenario is simple...I have one admin user and one customer user and I have also two lists. The customer user doesn't have permission to second list...The customer user can only add item in first list...So I have rewrite save function so that if user press Save button first new item will be created in second list and then in first list. The problem is that customer user doesn't have permission to the second list so there is an error...I understand why it is so...In SSOM I can use runwithelevated and everything works...in SharePoint Online (JSOM) this is not possible...I also understand why because of current context...but I was thinking that if I use this extension The customer user will be able to write the item to second list with my admin user account and to first list like himself. So very simple scenario...I know that I can achieve this with azure services but I need better solution because customer doesn't want to pay extra money for azure...They have only SharePoint Online...I know that this is not very expensive service but just simply many customer doesn't want this....
So again I think that my thoughts were wrong about working with node.js because I was thinking that it will works directly on SharePoint online without any extra service. Hmm...Again thank you for your help... Maybe what you think what is the best way to approach this permission problem... 
Thank you...

**Comment by koltyakov** [comment]
What modifications did you get to apply to `pnpjs.es5.umd.bundle.min.js`?

> My scenario is simple...

If a user has no permissions to a list he/she can't write to it client-side. There is no such a thing like `runwithelevated` in the client-side world. Instead of this, a server-side solution should take care of it.

The most simple and straightforward solution would be an Azure Function as a web-service secured with AAD, where most of the client-side logic can be reused within Node.js functions. If one familiar with JS dev, functions would be the simplest way of extending the logic. On small amounts, Azure Functions are extremely cheap.

Next, scheduled Azure Function, WebJob or Windows Scheduler or cron processes can be used to sync the lists on a scheduled basis. It's up to a decision where to host the scheduler. An advantage here is the same code base in a Node.js process.

MS Flow (modern workflow) in SPO also can solve the task.

And the final option - classic Workflow.

**Comment by enti333** [comment]
Hello. Thank you very much for explanation of this and I understand it right now. For me for right now will be to use azure functions. 
In pnpjs.es5.umd.bundle.min.js I must remove  use strict because there was every time some problem on Internet Explorer 11. I don't know why but after removing everything starts to work. 
And again Thank you very much Andrew for you help.:)
