### ISSUE TITLE
How to pass username and password

### ISSUE THREAD

**Issue by peterremote1980** [koltyakov/sp-pnp-node#12]
Hi
   How to pass username and password by strings?
thanks
From Peter

**Comment by koltyakov** [comment]
Hi @peterremote1980, 

It can be done within auth options. Sample: https://github.com/koltyakov/sp-pnp-node#factory-example

![image](https://user-images.githubusercontent.com/7816483/56457345-e4ad3b80-6381-11e9-8b7c-899663b11d99.png)

where authOptions are different possible auth options from [node-sp-auth](https://github.com/s-kainet/node-sp-auth#getauthurl-credentialoptions).

**Comment by peterremote1980** [comment]
Thanks, do you mean i programatically create config/private.json?

**Comment by koltyakov** [comment]
private.json is a way to store credentials locally, e.g. within publishing or automation pipelines with the capability of switching between different configs. But private.json is not required if app's logic assumes another source.

```typescipt
import { sp } from '@pnp/sp';
import { PnpNode, IPnpNodeSettings } from 'sp-pnp-node';

const config = require('../config/private.json');

const { siteUrl, username, password } = config; // source of this data can be any

const pnpNodeSettings: IPnpNodeSettings = {
  siteUrl: siteUrl,
  config: {
    headlessMode: true,
    saveConfigOnDisk: false
  },
  authOptions: {
    username,
    password
  }
};

const fetchClient = new PnpNode(pnpNodeSettings);
sp.setup({
  sp: {
    fetchClientFactory: () => fetchClient,
    baseUrl: config.siteUrl // Optional if siteUrl is in IPnpNodeSettings or in case of `new Web(url)`
  }
});
```

**Comment by JojiePalahang** [comment]
@koltyakov  - how can we pass domain? in `authOptions`

**Comment by koltyakov** [comment]
@JojiePalahang [check this out](https://github.com/s-kainet/node-sp-auth/wiki/SharePoint-on-premise-user-credentials-authentication), "domain" property (surprise!) or by including it in "username" in "username@contoso.com" or "contoso\\\\username" formats.
