### ISSUE TITLE
Add new row to existing list

### ISSUE THREAD

**Issue by polymer-coder** [koltyakov/sp-pnp-node#30]
Hi! 

Do you have an example of how to add a row of information to an existing list? Let's say the list has these fields:

- Title 
- Name 
- Age

**Comment by koltyakov** [comment]
Hi @polymer-coder,

sp-pnp-node is a library to run PnPjs in Node.js environment, it doesn’t add any specifics to how to consume SharePoint REST API with PnPjs. So the PnPjs docs and articles are relevant.

Please check the docs for working with lists items https://pnp.github.io/pnpjs/sp/items/#add-items

Hope this helps.

**Comment by polymer-coder** [comment]
@koltyakov thanks for the direction! Worked like a charm.

```
const { Web } = require("@pnp/sp");
const { PnpNode } = require("sp-pnp-node");

new PnpNode()
  .init()
  .then(async (settings) => {


    const web = new Web(settings.siteUrl);

    const entry = {
      Title: "1",
      Name: "John Doe",
      Age: 25,
    };
    await web
      .getList("/sites/<your site>/Lists/<your list>/AllItems.aspx")
      .items.add(entry);
  
  })
  .catch(console.error);  
```
