### ISSUE TITLE
Create end-to-end react-redux example

### ISSUE THREAD

**Issue by kayodebristol** [koltyakov/sp-pnp-node#8]
@koltyakov 
 After implementing your end-to-end create-react-app solution for sp-rest-proxy, I used sp-rest-proxy in a react-redux project. Again, it worked beautifully. Then I started thinking how the approach could work for sp-pnp-node or perhaps a new project, but not with plain react. Including sp-pnp-node won't work in a react component, but a redux action in a separate file might not suffer the same problems. For large scale dev, react-redux is superior to react alone. Also, it is my understanding that pnp has some problems with [post operations when leveraging sp-rest-proxy](https://github.com/koltyakov/sp-rest-proxy#some-additional-info). I'm not certain, but leveraging the sp-pnp-node fetchClient could be made to work. 
Potential issues: 
1. Calling the sp-pnp-node fetchClient only in Dev or outside of SharePoint, but using default pnp when in SharePoint
2. Complexity; stack would need react redux react-redux at a minimum. I would include redux-thunk to handle async redux actions.  

Benefits: 
1. Full pnp support, including post SharePoint data option while working with the dev tool chain 
2. Potential for SharePoint integrated [PWA](https://en.wikipedia.org/wiki/Progressive_web_app)
3. Add [pouchDB](https://pouchdb.com/)  or  [rxDB](https://github.com/pubkey/rxdb) to create an Offline-SharePoint-PWA; Use your SharePoint apps with no internet connection... sync when back online. 
4. I know this last one might sound really crazy... but, bear with me, a distributed, client-side workflow framework, orchestrated from SharePoint. Workflows should be centrally managed, but who says that they must be centrally executed. I've got clients for that.

**Comment by koltyakov** [comment]
Hey @kayodebristol ,

Glad that generic react setup example worked for you.
`sp-pnp-node` was made to run `sp-pnp-js` (PnP JS Core) outside browser in Node.js project on server.
`sp-pnp-js` should be used in browser.

I've just tried `sp-pnp-js` with React setup. Additional steps:

1\. Install dependency

```bash
npm install sp-pnp-js --save
```

2\. Import is in `app.js`

```javascript
import * as pnp from 'sp-pnp-js';
window.$pnp = pnp; // Just as an experiment to  run some requests in a console (in Chrome, for IE ES6-Promise and Fetch shims should be loaded too)
```

3\. Run basic requests:

```javascript
$pnp.sp.web.lists.select('Title').get().then(lists => {
  console.log(lists.map(list => list.Title));
}); // Just get a list of lists on the web - works

$pnp.sp.web.lists.getByTitle('TEST_EBS').items.get().then(console.log);
// Get items for a randon list - works

$pnp.sp.web.lists.getByTitle('TEST_EBS').items.add({ Title: '1243' }).then(console.log);
// Random POST request for adding items - also works
```
In this mode (with React proxy) a lot should work. Including most cases with POST requests. The only issue I know will be is batch requests, as correct SharePoint URLs should be send in multipart body content.

PWA/offline modes - need to think it out.
Offline modes can be implemented yet on limited predictable structures and processes. Tightly depended on a specific task.

**Comment by kayodebristol** [comment]
@koltyakov 
Good to know that most operations, even posts, will work with the proxy.
 
Looking at [browserify](http://browserify.org/). I just can't accept that the browsers JavaScript engine is incapable of formatting rest requests in a way that SharePoint would accept them. If node can do it, then the browser should be able to as well. But, I guess this is why they say ignorance is bliss. Cause I just don't know enough to realize that it might in fact be impossible. But it would be awesome if it could be done.

**Comment by kayodebristol** [comment]
@koltyakov
Browserify appears to be the wrong direction.  After some research,  service-worker based rewrite of the sp auth module seems a better approach.  Service Worker would catch fetch requests and reconfigure them based on environment,  SharePoint, outside of SharePoint, or offline.  Forward request if in SharePoint,  reformat request if outside of SharePoint,  return results from cache if offline.
So,  this issue will be closed and I'll start work on my very first github project. Hope it doesn't suck. 

As for offline first SharePoint,  I propose an event receiver list. One column multi line text list,  takes JSON style event. Traditional Server side workflow creates views based on the event.  I.e.,  event type: ADD_TROUBLE_TICKET,  Fields: blah,  blah, blah,  target: trouble ticket list;

Generic Workflow would create a new entry in a traditional style trouble ticket list. 

Event list is immutable,  traditional SharePoint lists would be mutable. 

Servers might also send commands to clients with events...  Event type: CLIENTS_MUST_UPDATE,  URL: https://newCode, key: hshdg%#:gfs,  target: client cmd list

Just an idea I've had for a while. You might say,  why not just build a SharePoint replacement with node,  JavaScript,  nosql, and containers? One problem at a time,  my friend.  One problem at a time.
