### ISSUE TITLE
Possible to use access_token obtained from azure ad with this?

### ISSUE THREAD

**Issue by nigel-dewar** [koltyakov/sp-pnp-node#9]
Hi There, this is a question. 

I am
Using node.js application using express. NOT using TypeScrupt.
Node App is hosted completely externally. It is NOT an addin.
Node Application authentications through Azure Ad, hence has an access_token available to use.

I did try just using the pnp-js-core library to do this like so

 tried setting the headers on the pnp setup object, like so

```
const pnp = require('sp-pnp-js')

pnp.setup({
                 sp: {
                     baseUrl: "https://mytenant.sharepoint.com",
                    headers: {
                         "Accept": "application/json;odata=verbose",
                         "Authorization": "Bearer " + token
                     }
                }
 }); 

pnp.sp.web.get().then(r => {
    console.log(r);
}); 
```

But got nowhere and just got errors about the headers not being set, even though they are of course.

Will the wrapper you created, allow me to do something like what I am trying to do here?

Many thanks in advance

Nigel Dewar

**Comment by koltyakov** [comment]
Hey @nigel-dewar,

Can you try something like:

```javascript
const pnp = require('sp-pnp-js');
const fetch = require('node-fetch');

global.Headers = fetch.Headers;
global.Request = fetch.Request;
global.Response = fetch.Response;

module.exports = (baseUrl, token) => {

  pnp.setup({
    sp: {
      fetchClientFactory: () => {
        return {
          fetch: (url, options) => {
            options.headers.set('Authorization', `Bearer ${token}`);
            return fetch(url, options);
          }
        };
      },
      baseUrl
    }
  });

  return pnp;

}
``` 

I know @eirikb uses such an approach with AAD apps.

**Comment by koltyakov** [comment]
Connecting with https://github.com/SharePoint/PnP-JS-Core/issues/717 and https://github.com/s-KaiNet/node-sp-auth/issues/31 as it's all about one single topic.

**Comment by koltyakov** [comment]
Was resolved https://github.com/SharePoint/PnP-JS-Core/issues/717#issuecomment-363366532
Closing the issue.
